# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/maps.proto
# Protobuf Python Version: 5.28.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
# from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# _runtime_version.ValidateProtobufRuntimeVersion(
#     _runtime_version.Domain.PUBLIC,
#     5,
#     28,
#     0,
#     '',
#     'proto/maps.proto'
# )
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10proto/maps.proto\x12\x0c\x65xample.maps\"\x17\n\tIdWrapper\x12\n\n\x02id\x18\x01 \x01(\r\"\x81\x01\n\nMapExample\x12.\n\x03ids\x18\x01 \x03(\x0b\x32!.example.maps.MapExample.IdsEntry\x1a\x43\n\x08IdsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12&\n\x05value\x18\x02 \x01(\x0b\x32\x17.example.maps.IdWrapper:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.maps_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MAPEXAMPLE_IDSENTRY']._loaded_options = None
  _globals['_MAPEXAMPLE_IDSENTRY']._serialized_options = b'8\001'
  _globals['_IDWRAPPER']._serialized_start=34
  _globals['_IDWRAPPER']._serialized_end=57
  _globals['_MAPEXAMPLE']._serialized_start=60
  _globals['_MAPEXAMPLE']._serialized_end=189
  _globals['_MAPEXAMPLE_IDSENTRY']._serialized_start=122
  _globals['_MAPEXAMPLE_IDSENTRY']._serialized_end=189
# @@protoc_insertion_point(module_scope)
